var courses = [
  {
    id: 1,
    title: 'Server Side Rendering with React and Redux',
    details: 'Build React, Redux, and React Router apps using Server Side Rendering (SSR), Isomorphic, and Universal JS techniques',
    auth: 'Stephen Grider',
    price: '9.99',
    img: 'reactServer.png',
  },
  {
    id: 2,
    title: 'React Native: Advanced Concepts',
    details: 'Master the advanced topics of React Native: Animations, Maps, Notifications, Navigation and More!',
    auth: 'Stephen Grider',
    price: '12.55',
    img: 'reactwebbase.png',
  },
  {
    id: 3,
    title: 'React JS Web Development - The Essentials Bootcamp',
    details: 'Bootcamp on the React.js essentials. Gain a strong foundation of the core concepts, and build exciting and useful apps!',
    auth: 'David Joshep',
    price: '15.99',
    img: 'reactWeb.png',
  },
  {
    id: 4,
    title: 'React Front To Back',
    details: 'Learn Modern React 16.8+ Including Hooks, Context API, Full Stack MERN & Redux By Building Real Life Projects',
    auth: 'Brad Traversy',
    price: '9.99',
    img: 'meran.png',
  },
  {
    id: 5,
    title: 'GraphQL with React: The Complete Developers Guide',
    details: 'Learn and master GraphQL by building real web apps with React and Node',
    auth: 'Stephen Grider',
    price: '9.99',
    img: 'grafqul.png',
  },
  {
    id: 6,
    title: 'Beginner Full Stack Web Development: HTML, CSS, React & Node',
    details: 'Learn web development with HTML, CSS, Bootstrap 4, ES6 React and Node',
    auth: 'Mark Wahlback',
    price: '11.99',
    img: 'fulstack.png',
  },
  {
    id: 7,
    title: 'Node with React: Fullstack Web Development',
    details: 'Build and deploy fullstack web apps with NodeJS, React, Redux, Express, and MongoDB.',
    auth: 'Waki Arrown',
    price: '14.99',
    img: 'nodeReact.png',
  },
  {
    id: 8,
    title: 'The Complete React Native + Hooks Course [2020 Edition]',
    details: 'Understand React Native v0.62.2 with Hooks, Context, and React Navigation.',
    auth: 'Max Huzon',
    price: '12.99',
    img: 'reactNative.png',
  },
  {
    id: 9,
    title: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
    details: 'Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!',
    auth: 'Maximilan',
    price: '13.90',
    img: 'reactjs.png',
  },
  {
    id: 10,
    title: 'Advanced React and Redux',
    details: 'Walkthroughs on advanced React v16.6.3 and Redux v4.0.0 - Authentication, Testing, Middlewares, HOC',
    auth: 'Mosh',
    price: '11.90',
    img: 'reactRedux.png',
  },
  {
    id: 11,
    title: 'The Complete JavaScript Course 2020: Build Real Projects!',
    details: 'Master JavaScript with the most complete course! Projects, challenges, quizzes, JavaScript ES6+, OOP, AJAX, Webpack',
    auth: 'Jonas Mat',
    price: '19.90',
    img: 'javascript01.png',
  },
  {
    id: 12,
    title: 'JavaScript: Understanding the Weird Parts',
    details: 'An advanced JavaScript course for everyone! Scope, closures, prototypes, build your own framework, and more.',
    auth: 'Anthony Alica',
    price: '14.90',
    img: 'javascript02.png',
  },
  {
    id: 13,
    title: 'Modern JavaScript From The Beginning',
    details: 'Learn and build projects with pure JavaScript (No frameworks or libraries)',
    auth: 'Brad Skoch',
    price: '13.90',
    img: 'javascript03.png',
  },
  {
    id: 14,
    title: 'JavaScript - The Complete Guide 2020 (Beginner + Advanced)',
    details: 'Modern JavaScript from the beginning - all the way up to JS expert level! THE must-have JavaScript resource in 2020.',
    auth: 'Mathu Mornel',
    price: '8.90',
    img: 'modernjs.png',
  },
  {
    id: 15,
    title: 'JavaScript: The Advanced Concepts',
    details: 'Learn modern advanced JavaScript practices and be in the top 10% of JavaScript developers',
    auth: 'Andreio Nion',
    price: '18.90',
    img: 'webdev.png',
  },
];

export default courses;
